# Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
  namespace: qa
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: ravi2krishna/ecomm
        ports:
        - containerPort: 80